"""
FinGuard 2026 — SOAR Pydantic Models.

Data models for investigations, agent results, audit records,
remediation actions, and HITL escalation workflows.
"""

from __future__ import annotations

import uuid
import time
from datetime import datetime
from enum import Enum
from typing import Any, Optional

from pydantic import BaseModel, Field


# ─── Enums ──────────────────────────────────────────────────────────────────


class InvestigationState(str, Enum):
    """State machine states for a SOAR investigation."""
    PENDING = "pending"
    TRIAGING = "triaging"
    INVESTIGATING = "investigating"
    REPORTING = "reporting"
    AWAITING_APPROVAL = "awaiting_approval"
    REMEDIATING = "remediating"
    CLOSED = "closed"
    FAILED = "failed"


class TriageVerdict(str, Enum):
    """Triage agent's classification of an alert."""
    IMMEDIATE_ACTION = "immediate_action"
    NEEDS_INVESTIGATION = "needs_investigation"
    FALSE_POSITIVE = "false_positive"


class RemediationAction(str, Enum):
    """Actions the legacy bridge can execute."""
    ACCOUNT_FREEZE = "account_freeze"
    TRANSACTION_HOLD = "transaction_hold"
    NO_ACTION = "no_action"


class EscalationStatus(str, Enum):
    """HITL escalation states."""
    PENDING = "pending"
    APPROVED = "approved"
    DENIED = "denied"
    TIMED_OUT = "timed_out"


# ─── Investigation & Alert Models ───────────────────────────────────────────


def _inv_id() -> str:
    return f"INV-{uuid.uuid4().hex[:12]}"


def _now_iso() -> str:
    return datetime.utcnow().isoformat() + "Z"


class FraudAlert(BaseModel):
    """Incoming fraud alert from Kafka high-risk topic."""
    alert_id: str = Field(default_factory=lambda: f"ALT-{uuid.uuid4().hex[:10]}")
    transaction_id: str
    user_id: str
    merchant_id: str
    device_id: str
    ip_address: str
    amount: float
    currency: str = "USD"
    timestamp: str
    fraud_score: float = Field(ge=0, le=1)
    risk_level: str
    reason_codes: dict[str, float] = Field(default_factory=dict)
    graph_contribution: float = 0.0
    temporal_contribution: float = 0.0
    biometric_contribution: float = 0.0


class Investigation(BaseModel):
    """Full investigation document stored in MongoDB."""
    investigation_id: str = Field(default_factory=_inv_id)
    alert: FraudAlert
    state: InvestigationState = InvestigationState.PENDING
    created_at: str = Field(default_factory=_now_iso)
    updated_at: str = Field(default_factory=_now_iso)
    triage_result: Optional[TriageResult] = None
    terminal_result: Optional[TerminalResult] = None
    compliance_result: Optional[ComplianceResult] = None
    remediation_result: Optional[RemediationResult] = None
    escalation_id: Optional[str] = None
    final_verdict: Optional[str] = None
    confidence: float = 0.0
    closed_at: Optional[str] = None


# ─── Agent Result Models ────────────────────────────────────────────────────


class TriageResult(BaseModel):
    """Output of the Triage Agent."""
    verdict: TriageVerdict
    confidence: float = Field(ge=0, le=1)
    risk_factors: list[str] = Field(default_factory=list)
    ensemble_score_analysis: str = ""
    velocity_check: dict[str, Any] = Field(default_factory=dict)
    amount_anomaly: dict[str, Any] = Field(default_factory=dict)
    graph_contagion: dict[str, Any] = Field(default_factory=dict)
    reasoning: str = ""
    timestamp: str = Field(default_factory=_now_iso)


class CLICommandResult(BaseModel):
    """Result of a single CLI command execution."""
    command: str
    exit_code: int
    stdout: str
    stderr: str
    executed_at: str = Field(default_factory=_now_iso)
    duration_ms: float = 0.0


class BlastRadiusNode(BaseModel):
    """A node discovered during blast radius mapping."""
    node_id: str
    node_type: str  # User, Device, IP, Merchant
    risk_score: float = 0.0
    distance: int = 0
    is_flagged: bool = False


class TerminalResult(BaseModel):
    """Output of the Terminal/CLI Agent."""
    cli_commands_executed: list[CLICommandResult] = Field(default_factory=list)
    blast_radius: list[BlastRadiusNode] = Field(default_factory=list)
    blast_radius_summary: str = ""
    ip_intelligence: dict[str, Any] = Field(default_factory=dict)
    network_diagnostics: dict[str, Any] = Field(default_factory=dict)
    graph_queries_run: int = 0
    suspicious_findings: list[str] = Field(default_factory=list)
    reasoning: str = ""
    timestamp: str = Field(default_factory=_now_iso)


class SARReport(BaseModel):
    """Suspicious Activity Report generated by the Compliance Agent."""
    sar_id: str = Field(default_factory=lambda: f"SAR-{uuid.uuid4().hex[:10]}")
    filing_type: str = "initial"
    subject_user_id: str
    activity_start: str
    activity_end: str
    total_amount: float
    activity_summary: str
    timeline: list[dict[str, Any]] = Field(default_factory=list)
    graph_connections: list[dict[str, Any]] = Field(default_factory=list)
    reason_codes: list[dict[str, Any]] = Field(default_factory=list)
    recommended_actions: list[str] = Field(default_factory=list)
    regulatory_categories: list[str] = Field(default_factory=list)
    markdown_report: str = ""
    generated_at: str = Field(default_factory=_now_iso)


class ComplianceResult(BaseModel):
    """Output of the Compliance Agent."""
    sar_report: SARReport
    regulatory_flags: list[str] = Field(default_factory=list)
    ecoa_compliant: bool = True
    bsa_aml_compliant: bool = True
    reasoning: str = ""
    timestamp: str = Field(default_factory=_now_iso)


# ─── Remediation Models ────────────────────────────────────────────────────


class FreezeResult(BaseModel):
    """Result of an account freeze via legacy bridge."""
    success: bool
    account_id: str
    action: RemediationAction
    bank_portal: str
    confirmation_id: Optional[str] = None
    screenshot_path: Optional[str] = None
    error: Optional[str] = None
    executed_at: str = Field(default_factory=_now_iso)


class RemediationResult(BaseModel):
    """Combined remediation outcome."""
    action_taken: RemediationAction
    freeze_result: Optional[FreezeResult] = None
    success: bool = False
    reasoning: str = ""
    timestamp: str = Field(default_factory=_now_iso)


# ─── Audit Models ──────────────────────────────────────────────────────────


class AgentAction(BaseModel):
    """Immutable audit record for every agent action."""
    action_id: str = Field(default_factory=lambda: f"ACT-{uuid.uuid4().hex[:10]}")
    investigation_id: str
    agent: str  # "triage", "terminal", "compliance", "remediation", "orchestrator"
    action: str  # "evaluate_alert", "execute_cli", "query_graph", "draft_sar", "freeze_account"
    timestamp: str = Field(default_factory=_now_iso)
    input_data: dict[str, Any] = Field(default_factory=dict)
    output_data: dict[str, Any] = Field(default_factory=dict)
    prev_hash: Optional[str] = None
    signature: Optional[str] = None


# ─── HITL Escalation Models ────────────────────────────────────────────────


class EscalationRequest(BaseModel):
    """Request to escalate an investigation to a human analyst."""
    escalation_id: str = Field(default_factory=lambda: f"ESC-{uuid.uuid4().hex[:10]}")
    investigation_id: str
    reason: str
    confidence: float
    investigation_summary: dict[str, Any] = Field(default_factory=dict)
    triage_result: Optional[TriageResult] = None
    terminal_result: Optional[TerminalResult] = None
    created_at: str = Field(default_factory=_now_iso)
    expires_at: Optional[str] = None
    status: EscalationStatus = EscalationStatus.PENDING


class EscalationDecision(BaseModel):
    """Analyst's decision on an escalation."""
    approved: bool
    analyst_id: str = "analyst-001"
    notes: str = ""
    decided_at: str = Field(default_factory=_now_iso)


# ─── Bank Portal Config ────────────────────────────────────────────────────


class BankPortalConfig(BaseModel):
    """Configuration for a legacy bank portal."""
    bank_name: str
    portal_url: str
    username_env: str = "BANK_USERNAME"
    password_env: str = "BANK_PASSWORD"
    login_url_path: str = "/login"
    accounts_url_path: str = "/accounts"
    # CSS selectors for DOM navigation
    selectors: dict[str, str] = Field(default_factory=lambda: {
        "username_input": "#username",
        "password_input": "#password",
        "login_button": "#login-btn",
        "account_search": "#account-search",
        "search_button": "#search-btn",
        "freeze_button": "#freeze-btn",
        "hold_button": "#hold-btn",
        "confirm_button": "#confirm-action",
        "status_message": "#status-message",
        "confirmation_id": "#confirmation-id",
    })


# Forward references for Investigation model
Investigation.model_rebuild()
