"""
Credit Line Fintech Solution — Phase 15: Treasury & Cryptographic Audit Router.

Exposes endpoints for cash sweeping simulations, Zero-Knowledge Solvency proofs,
and automated board deck PowerPoint compile.
"""

from __future__ import annotations
import os
import tempfile
from typing import Dict, List, Any, Optional
from fastapi import APIRouter, HTTPException, Depends
from fastapi.responses import FileResponse, JSONResponse
from pydantic import BaseModel, Field

from services.treasury.treasury_optimizer import TreasuryOptimizer
from services.zk_audit.zk_solvency_prover import ZKSolvencyProver
from services.reporting.board_deck_generator import BoardDeckGenerator

router = APIRouter(prefix="/api/v1/treasury-audit", tags=["Treasury & Cryptographic Audit (Phase 15)"])

# ─── Singletons ──────────────────────────────────────────────────────────────

_optimizer = TreasuryOptimizer()
_prover = ZKSolvencyProver()
_deck_generator = BoardDeckGenerator()

# Default mock ledger for solvency audits
DEFAULT_LEDGER = {
    "CashAndEquivalents": {"type": "ASSET", "balance": 18200000.0},
    "AlternativeCreditReceivables": {"type": "ASSET", "balance": 6400000.0},
    "TreasuryHoldings": {"type": "ASSET", "balance": 3900000.0},
    "AccountsPayable": {"type": "LIABILITY", "balance": 4100000.0},
    "SovereignCreditDebt": {"type": "LIABILITY", "balance": 4100000.0},
    "ShareholderEquity": {"type": "EQUITY", "balance": 20300000.0}
}


# ─── Request/Response Models ──────────────────────────────────────────────────

class SweepRequest(BaseModel):
    current_cash: float = Field(18200000.0, description="Current corporate ledger cash balance in INR")
    predicted_min_cash_30d: float = Field(15500000.0, description="CFO predicted minimum cash level in next 30 days")
    reserve_threshold: float = Field(1200000.0, description="Corporate emergency cash reserves threshold in INR")


class ZKProveRequest(BaseModel):
    ledger_accounts: Optional[Dict[str, Dict[str, Any]]] = Field(None, description="Optional double-entry account snapshot")


class ZKVerifyRequest(BaseModel):
    proof_payload: Dict[str, Any] = Field(..., description="Zero-Knowledge proof structure generated by prove endpoint")


class BoardDeckRequest(BaseModel):
    quarterly_revenue: Optional[float] = None
    net_income: Optional[float] = None
    total_assets: Optional[float] = None
    total_liabilities: Optional[float] = None
    zk_merkle_root: Optional[str] = None
    runway_days: Optional[int] = None
    cash_swept: Optional[float] = None
    yield_earned_projected_30d: Optional[float] = None
    negotiations_sent: Optional[int] = None
    active_users: Optional[int] = None


# ─── Endpoints ───────────────────────────────────────────────────────────────

@router.post("/sweep")
async def sweep_idle_cash(req: SweepRequest):
    """
    Evaluate predicted cash flow and sweep excess reserves into treasury bills / money market funds
    using the Sharpe Ratio optimization engine.
    """
    result = _optimizer.optimize_allocation(
        current_cash=req.current_cash,
        predicted_min_cash_30d=req.predicted_min_cash_30d,
        reserve_threshold=req.reserve_threshold
    )
    return result


@router.post("/zk/prove")
async def generate_solvency_proof(req: ZKProveRequest):
    """
    Construct a Merkle tree of ledger state and output a simulated zk-SNARK solvency proof.
    """
    ledger = req.ledger_accounts or DEFAULT_LEDGER
    proof = _prover.generate_proof(ledger)
    return proof


@router.post("/zk/verify")
async def verify_solvency_proof(req: ZKVerifyRequest):
    """
    Validate an uploaded/pasted zk-SNARK solvency proof payload.
    Checks solvency inequality and double-entry invariants.
    """
    result = _prover.verify_proof(req.proof_payload)
    return result


@router.post("/reporting/board-deck")
async def generate_board_deck(req: BoardDeckRequest):
    """
    Compile corporate metrics and stream a beautifully generated Board presentation.
    """
    # Merge requests parameters with system metrics
    data_payload = {
        "quarterly_revenue": req.quarterly_revenue or 18500000.0,
        "net_income": req.net_income or 4200000.0,
        "total_assets": req.total_assets or 28500000.0,
        "total_liabilities": req.total_liabilities or 8200000.0,
        "zk_merkle_root": req.zk_merkle_root or "0f5c1d683aee4b12c8b910e54d8174f828a1c9ee",
        "runway_days": req.runway_days or 90,
        "cash_swept": req.cash_swept or 12500000.0,
        "yield_earned_projected_30d": req.yield_earned_projected_30d or 54300.0,
        "negotiations_sent": req.negotiations_sent or 4,
        "active_users": req.active_users or 1450
    }

    compiled_deck_data = _deck_generator.compile_board_data(data_payload)
    
    # Generate presentation files
    temp_dir = tempfile.gettempdir()
    pptx_filename = f"credit_line_board_presentation_{int(data_payload['yield_earned_projected_30d'])}.pptx"
    pptx_path = os.path.join(temp_dir, pptx_filename)

    success = _deck_generator.generate_pptx_deck(compiled_deck_data, pptx_path)

    if success:
        return FileResponse(
            path=pptx_path,
            filename=pptx_filename,
            media_type="application/vnd.openxmlformats-officedocument.presentationml.presentation"
        )
    else:
        # Fallback response returning compiled slide data as JSON if python-pptx is missing
        fallback_filename = pptx_path.replace(".pptx", "_fallback.json")
        return JSONResponse(
            status_code=200,
            content={
                "message": "PowerPoint PPTX compiler was unavailable. Returned slides as JSON payload.",
                "download_json_fallback": True,
                "slides": compiled_deck_data["slides"],
                "metadata": compiled_deck_data["metadata"]
            }
        )
