"""
FinGuard 2026 — Financial Digital Twin: Citizen Agent Archetypes.

Agent-Based Model (ABM) that simulates a synthetic economy of 100,000+
AI "Citizens" with distinct behavioral profiles. Each agent generates
realistic transaction streams with complex seasonality, social graph
connections, and alternative credit data.

Citizen archetypes:
  1. SalaryEarner      — Regular income, predictable spending, low fraud risk
  2. GigWorker         — Irregular income, variable spending, medium risk
  3. UnbankedCitizen   — No traditional bank, mobile money, utility-only credit
  4. FraudSyndicate    — Coordinated rings, layering, smurfing, high-volume

Each agent's transactions feed directly into the Kafka ingestion layer,
creating a photorealistic simulation indistinguishable from live production data.
"""

from __future__ import annotations

import math
import random
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any


class CitizenType(str, Enum):
    SALARY_EARNER = "salary_earner"
    GIG_WORKER = "gig_worker"
    UNBANKED = "unbanked"
    FRAUD_SYNDICATE = "fraud_syndicate"


@dataclass
class Transaction:
    """A synthetic transaction generated by a citizen agent."""
    transaction_id: str
    user_id: str
    merchant_id: str
    amount: float
    currency: str
    timestamp: float
    device_id: str
    ip_address: str
    category: str
    is_fraud: bool = False
    fraud_type: str = ""

    def to_dict(self) -> dict[str, Any]:
        return {
            "transaction_id": self.transaction_id,
            "user_id": self.user_id,
            "merchant_id": self.merchant_id,
            "amount": round(self.amount, 2),
            "currency": self.currency,
            "timestamp": self.timestamp,
            "device_id": self.device_id,
            "ip_address": self.ip_address,
            "category": self.category,
            "is_fraud": self.is_fraud,
            "fraud_type": self.fraud_type,
        }


@dataclass
class CreditDataPoint:
    """Alternative credit data for unbanked citizens."""
    user_id: str
    utility_payment_score: float
    telco_months_active: int
    mobile_topup_consistency: float
    rent_payment_history: int
    digital_wallet_balance_avg: float
    timestamp: float


# ─── Base Citizen Agent ────────────────────────────────────────────────

class CitizenAgent:
    """Base class for all citizen agents in the Digital Twin."""

    def __init__(
        self,
        user_id: str | None = None,
        citizen_type: CitizenType = CitizenType.SALARY_EARNER,
        monthly_income: float = 3000.0,
        spending_ratio: float = 0.7,
    ):
        self.user_id = user_id or f"USR-{uuid.uuid4().hex[:8]}"
        self.citizen_type = citizen_type
        self.monthly_income = monthly_income
        self.spending_ratio = spending_ratio

        self.device_id = f"DEV-{uuid.uuid4().hex[:6]}"
        self.ip_address = f"{random.randint(10,199)}.{random.randint(0,255)}.{random.randint(0,255)}.{random.randint(1,254)}"
        self.balance = monthly_income * random.uniform(0.5, 3.0)
        self.merchants = self._generate_preferred_merchants()
        self._tx_count = 0

    def _generate_preferred_merchants(self) -> list[str]:
        """Generate a set of preferred merchants for this citizen."""
        categories = ["grocery", "restaurant", "transport", "utility",
                      "entertainment", "clothing", "electronics", "health"]
        n = random.randint(3, 8)
        return [f"MRC-{cat[:3].upper()}-{uuid.uuid4().hex[:4]}"
                for cat in random.sample(categories, n)]

    def step(self, current_time: float) -> list[Transaction]:
        """Generate transactions for one simulation step (1 hour)."""
        raise NotImplementedError

    def _base_spending_probability(self, hour: int, day_of_week: int) -> float:
        """
        Seasonality engine: probability of making a transaction this hour.

        Incorporates:
          - Time of day (peak: 10-14, 18-21)
          - Day of week (weekends higher for leisure)
          - Month-start rent/bill payments
        """
        # Hourly pattern: bimodal peak
        hourly = 0.3 * math.exp(-0.5 * ((hour - 12) / 3) ** 2) + \
                 0.2 * math.exp(-0.5 * ((hour - 19) / 2) ** 2)

        # Weekend boost
        if day_of_week >= 5:
            hourly *= 1.3

        return min(hourly, 0.9)

    def _generate_tx(
        self, current_time: float, amount: float,
        category: str = "general", is_fraud: bool = False,
        fraud_type: str = "",
    ) -> Transaction:
        """Generate a single transaction."""
        self._tx_count += 1
        merchant = random.choice(self.merchants)
        return Transaction(
            transaction_id=f"TX-{uuid.uuid4().hex[:10]}",
            user_id=self.user_id,
            merchant_id=merchant,
            amount=amount,
            currency="USD",
            timestamp=current_time,
            device_id=self.device_id,
            ip_address=self.ip_address,
            category=category,
            is_fraud=is_fraud,
            fraud_type=fraud_type,
        )


# ─── Archetype: Salary Earner ─────────────────────────────────────────

class SalaryEarner(CitizenAgent):
    """
    Regular income, predictable spending patterns.
    Monthly salary deposit, recurring bills, stable merchants.
    """

    def __init__(self, **kwargs):
        kwargs.setdefault("citizen_type", CitizenType.SALARY_EARNER)
        kwargs.setdefault("monthly_income", random.uniform(2500, 8000))
        kwargs.setdefault("spending_ratio", random.uniform(0.6, 0.8))
        super().__init__(**kwargs)
        self.payday = random.choice([1, 15, 25])  # Day of month

    def step(self, current_time: float) -> list[Transaction]:
        txs = []
        tm = time.gmtime(current_time)
        hour, dow, dom = tm.tm_hour, tm.tm_wday, tm.tm_mday

        # Payday: salary deposit (skip — external)
        # Regular spending
        prob = self._base_spending_probability(hour, dow) * 0.8
        if random.random() < prob:
            daily_budget = (self.monthly_income * self.spending_ratio) / 30
            amount = random.gauss(daily_budget / 3, daily_budget / 6)
            amount = max(2.0, abs(amount))
            categories = ["grocery", "restaurant", "transport", "coffee"]
            txs.append(self._generate_tx(
                current_time, amount, random.choice(categories)))

        # Monthly bills (1st-5th of month)
        if dom <= 5 and hour == 9 and random.random() < 0.3:
            bill = random.choice(["utility", "rent", "insurance", "subscription"])
            amount = random.uniform(50, 1200) if bill == "rent" else random.uniform(30, 200)
            txs.append(self._generate_tx(current_time, amount, bill))

        return txs


# ─── Archetype: Gig Worker ────────────────────────────────────────────

class GigWorker(CitizenAgent):
    """
    Irregular income, variable spending, multiple payment sources.
    Higher transaction frequency but lower average amounts.
    """

    def __init__(self, **kwargs):
        kwargs.setdefault("citizen_type", CitizenType.GIG_WORKER)
        kwargs.setdefault("monthly_income", random.uniform(1500, 5000))
        kwargs.setdefault("spending_ratio", random.uniform(0.7, 0.95))
        super().__init__(**kwargs)

    def step(self, current_time: float) -> list[Transaction]:
        txs = []
        tm = time.gmtime(current_time)
        hour, dow = tm.tm_hour, tm.tm_wday

        prob = self._base_spending_probability(hour, dow) * 1.2
        # Gig workers have burstier patterns
        if random.random() < prob:
            # Small frequent transactions
            amount = random.expovariate(1.0 / 25.0)  # Mean $25
            amount = max(3.0, min(amount, 500.0))
            categories = ["food", "transport", "tools", "fuel", "phone_topup"]
            txs.append(self._generate_tx(
                current_time, amount, random.choice(categories)))

        # Occasional larger purchases after "good day"
        if random.random() < 0.02 and 12 <= hour <= 22:
            amount = random.uniform(100, 800)
            txs.append(self._generate_tx(
                current_time, amount, "electronics"))

        return txs


# ─── Archetype: Unbanked Citizen ──────────────────────────────────────

class UnbankedCitizen(CitizenAgent):
    """
    No traditional bank account. Uses mobile money, utility payments,
    and community lending. Generates alternative credit data.
    """

    def __init__(self, **kwargs):
        kwargs.setdefault("citizen_type", CitizenType.UNBANKED)
        kwargs.setdefault("monthly_income", random.uniform(800, 2500))
        kwargs.setdefault("spending_ratio", random.uniform(0.85, 0.98))
        super().__init__(**kwargs)
        self.mobile_money_provider = random.choice(["M-Pesa", "GCash", "Paytm", "Wave"])
        self.utility_payment_consistency = random.uniform(0.5, 0.95)

    def step(self, current_time: float) -> list[Transaction]:
        txs = []
        tm = time.gmtime(current_time)
        hour, dow, dom = tm.tm_hour, tm.tm_wday, tm.tm_mday

        # Mobile money transfers (primary payment method)
        prob = self._base_spending_probability(hour, dow) * 0.6
        if random.random() < prob:
            amount = random.uniform(2, 80)
            txs.append(self._generate_tx(
                current_time, amount, "mobile_money"))

        # Phone topups (critical for credit scoring)
        if random.random() < 0.05 and 8 <= hour <= 20:
            amount = random.choice([5, 10, 20, 50])
            txs.append(self._generate_tx(
                current_time, amount, "phone_topup"))

        # Utility payments (1st-10th of month)
        if dom <= 10 and hour == 10 and random.random() < self.utility_payment_consistency * 0.15:
            utility_type = random.choice(["electricity", "water", "gas"])
            amount = random.uniform(15, 80)
            txs.append(self._generate_tx(
                current_time, amount, utility_type))

        return txs

    def generate_credit_data(self, current_time: float) -> CreditDataPoint:
        """Generate alternative credit data for this citizen."""
        return CreditDataPoint(
            user_id=self.user_id,
            utility_payment_score=random.uniform(400, 800),
            telco_months_active=random.randint(3, 60),
            mobile_topup_consistency=self.utility_payment_consistency,
            rent_payment_history=random.randint(0, 48),
            digital_wallet_balance_avg=random.uniform(10, 500),
            timestamp=current_time,
        )


# ─── Archetype: Fraud Syndicate ───────────────────────────────────────

class FraudSyndicate(CitizenAgent):
    """
    Coordinated fraud ring. Generates layered money laundering,
    smurfing, and account takeover patterns.

    Attack patterns:
      - Smurfing: many small txs just under reporting threshold
      - Layering: rapid transfers between mule accounts
      - Card testing: small txs to verify stolen credentials
      - Bust-out: build trust then large fraudulent purchase
    """

    def __init__(
        self,
        ring_members: list[str] | None = None,
        attack_phase: str = "dormant",
        **kwargs,
    ):
        kwargs.setdefault("citizen_type", CitizenType.FRAUD_SYNDICATE)
        kwargs.setdefault("monthly_income", random.uniform(1000, 3000))
        super().__init__(**kwargs)

        self.ring_members = ring_members or [
            f"USR-MULE-{uuid.uuid4().hex[:4]}" for _ in range(random.randint(3, 8))]
        self.attack_phase = attack_phase  # dormant, building, active, layering
        self._phase_step = 0
        self._compromised_ips = [
            f"{random.randint(100,200)}.{random.randint(0,255)}.{random.randint(0,255)}.{random.randint(1,254)}"
            for _ in range(5)]

    def step(self, current_time: float) -> list[Transaction]:
        txs = []
        self._phase_step += 1

        # Phase transitions
        if self.attack_phase == "dormant" and self._phase_step > random.randint(100, 500):
            self.attack_phase = "building"
            self._phase_step = 0

        elif self.attack_phase == "building" and self._phase_step > random.randint(50, 200):
            self.attack_phase = "active"
            self._phase_step = 0

        elif self.attack_phase == "active" and self._phase_step > random.randint(20, 80):
            self.attack_phase = "layering"
            self._phase_step = 0

        elif self.attack_phase == "layering" and self._phase_step > random.randint(10, 30):
            self.attack_phase = "dormant"
            self._phase_step = 0

        # Generate fraud transactions based on phase
        if self.attack_phase == "building":
            # Card testing: small amounts to verify credentials
            if random.random() < 0.3:
                amount = random.uniform(0.50, 5.00)
                txs.append(self._generate_tx(
                    current_time, amount, "card_test",
                    is_fraud=True, fraud_type="card_testing"))

        elif self.attack_phase == "active":
            # Smurfing: many transactions just under $10,000 threshold
            if random.random() < 0.5:
                amount = random.uniform(8000, 9999)
                txs.append(self._generate_tx(
                    current_time, amount, "transfer",
                    is_fraud=True, fraud_type="smurfing"))

        elif self.attack_phase == "layering":
            # Rapid transfers between mule accounts
            n_transfers = random.randint(2, 6)
            for _ in range(n_transfers):
                amount = random.uniform(500, 5000)
                tx = self._generate_tx(
                    current_time, amount, "p2p_transfer",
                    is_fraud=True, fraud_type="layering")
                # Rotate IP to evade detection
                tx.ip_address = random.choice(self._compromised_ips)
                txs.append(tx)

        else:
            # Dormant: normal-looking behavior to build trust
            if random.random() < 0.1:
                amount = random.uniform(10, 100)
                txs.append(self._generate_tx(
                    current_time, amount, "grocery"))

        return txs
