import { useState, useEffect, useCallback, useRef } from 'react';
import {
  FileText, CheckCircle2, AlertTriangle,
  Send, ShieldAlert, Cpu, Sliders, X, Inbox,
  BarChart3, RefreshCw, Layers, ShieldCheck, UploadCloud, Info
} from 'lucide-react';
import {
  AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  ReferenceLine
} from 'recharts';
import { apiGet, apiPost } from '../../lib/api';
import { cn } from '../../lib/utils';
import { useAppStore } from '../../store/useAppStore';

// ─── Interfaces ──────────────────────────────────────────────────────────────

interface ForecastData {
  days: number[];
  base_case: number[];
  worst_case: number[];
  best_case: number[];
  std_dev: number;
  trigger_report: {
    triggered: boolean;
    crunch_day: number;
    severity: string;
    message: string;
  };
}

interface InboxItem {
  id: string;
  type: 'term_negotiation' | 'budget_rebalance';
  status: 'PENDING' | 'APPROVED' | 'REJECTED';
  title: string;
  vendor?: string;
  category?: string;
  current_terms?: string;
  proposed_terms?: string;
  email_subject?: string;
  email_body?: string;
  description?: string;
  cuts?: Array<{
    department: string;
    original: number;
    proposed: number;
    reduction_pct: number;
    action: string;
  }>;
  total_savings?: number;
  created_at: string;
  processed_at: string | null;
}

interface ContractAuditResult {
  filename: string;
  detected_terms: string;
  clause: string;
  match_confidence: number;
  extracted_days: number;
  violations: Array<{
    invoice_ref: string;
    invoice_date: string;
    payment_ref: string;
    payment_date: string;
    days_to_pay: number;
    allowed_days: number;
    excess_days: number;
    status: string;
    severity: string;
  }>;
  violations_count: number;
}

interface Toast {
  id: string;
  message: string;
  type: 'success' | 'error' | 'info';
}

// ─── Sample Contract Template for Demo ──────────────────────────────────────

const DEFAULT_CONTRACT_INPUT = `MASTER SERVICE AGREEMENT

This Master Service Agreement ("Agreement") is entered into by and between Credit Line Solutions (the "Company") and VND-CONSULT-004 ("Consultant").

1. PAYMENT TERMS
Invoices will be generated by the Consultant on the first calendar day of each month following service delivery. Payment terms are strictly Net-15 payment required from the date of invoice. Late payments shall accrue interest at a rate of 1.5% per month.

2. SLA AND COMPLIANCE
Consultant commits to a response SLA of 2 hours for critical tickets. If SLA response exceeds 4 hours, a penalty of 5% of monthly billable value applies.`;


export default function ExecutiveStrategyRoom() {
  const { theme, font } = useAppStore();

  // Scenario States
  const [salesGrowth, setSalesGrowth] = useState<number>(0);
  const [churnRate, setChurnRate] = useState<number>(0);
  const [interestShock, setInterestShock] = useState<number>(0);
  const [reserveFloor, setReserveFloor] = useState<number>(1200000);

  // Loaded Data States
  const [forecast, setForecast] = useState<ForecastData | null>(null);
  const [inbox, setInbox] = useState<InboxItem[]>([]);
  const [selectedInboxItem, setSelectedInboxItem] = useState<InboxItem | null>(null);
  
  // Contract Ingestion States
  const [contractText, setContractText] = useState<string>(DEFAULT_CONTRACT_INPUT);
  const [contractFile, setContractFile] = useState<string>('vnd_consult_agreement_2026.txt');
  const [auditResult, setAuditResult] = useState<ContractAuditResult | null>(null);

  // UI State Panels
  const [activeTab, setActiveTab] = useState<'forecasting' | 'inbox' | 'rag'>('forecasting');
  const [loadingForecast, setLoadingForecast] = useState<boolean>(false);
  const [loadingAudit, setLoadingAudit] = useState<boolean>(false);
  const [editedEmailBody, setEditedEmailBody] = useState<string>('');

  // Toast System State
  const [toasts, setToasts] = useState<Toast[]>([]);
  const toastCounter = useRef<number>(0);

  const addToast = useCallback((message: string, type: Toast['type'] = 'success') => {
    const id = `toast-${++toastCounter.current}`;
    setToasts((prev) => [...prev, { id, message, type }]);
    setTimeout(() => {
      setToasts((prev) => prev.filter((t) => t.id !== id));
    }, 4000);
  }, []);

  // ─── Data Load Fetchers ───────────────────────────────────────────────────

  const runForecast = useCallback(async (shocks = {}) => {
    setLoadingForecast(true);
    try {
      const data = await apiPost<ForecastData>('/executive/forecast', {
        sales_growth: salesGrowth,
        churn_rate: churnRate,
        macro_interest_rate: interestShock / 100.0, // Convert bps to decimal
        reserve_threshold: reserveFloor,
        ...shocks
      });
      setForecast(data);
      if (data.trigger_report.triggered) {
        addToast(data.trigger_report.message, 'info');
      }
    } catch {
      addToast('Failed to compute forecasting model. Ensure backend is running.', 'error');
    } finally {
      setLoadingForecast(false);
    }
  }, [salesGrowth, churnRate, interestShock, reserveFloor, addToast]);

  const loadInbox = useCallback(async () => {
    try {
      const data = await apiGet<{ items: InboxItem[] }>('/executive/negotiations/inbox');
      setInbox(data.items);
      if (data.items.length > 0) {
        // Automatically select first pending item if none selected
        const pending = data.items.find(i => i.status === 'PENDING');
        setSelectedInboxItem(pending || data.items[0]);
      }
    } catch {
      // Offline fallback initialized in state
    }
  }, []);

  const runContractAudit = async () => {
    setLoadingAudit(true);
    try {
      const data = await apiPost<ContractAuditResult>('/executive/contracts/upload', {
        filename: contractFile,
        content: contractText
      });
      setAuditResult(data);
      addToast(`Ingested and audited contract: terms detected ${data.detected_terms}`, 'success');
      if (data.violations_count > 0) {
        addToast(`Ledger Audit: found ${data.violations_count} payment SLA violations!`, 'error');
      }
    } catch {
      addToast('Failed to analyze contract. Ensure backend is running.', 'error');
    } finally {
      setLoadingAudit(false);
    }
  };

  const handleAction = async (itemId: string, decision: 'APPROVE' | 'REJECT' | 'UPDATE') => {
    try {
      const result = await apiPost<{ success: boolean; item: InboxItem; message: string }>('/executive/negotiations/action', {
        action_id: itemId,
        decision,
        custom_body: decision === 'APPROVE' || decision === 'UPDATE' ? editedEmailBody : undefined
      });
      if (result.success) {
        addToast(result.message, decision === 'REJECT' ? 'info' : 'success');
        // Reload Inbox
        loadInbox();
      }
    } catch {
      addToast('Error processing decision code.', 'error');
    }
  };

  // ─── Initializer ──────────────────────────────────────────────────────────

  useEffect(() => {
    runForecast();
    loadInbox();
  }, [runForecast, loadInbox]);

  useEffect(() => {
    if (selectedInboxItem) {
      setEditedEmailBody(selectedInboxItem.email_body || '');
    }
  }, [selectedInboxItem]);

  // ─── Chart Data Compiler ──────────────────────────────────────────────────

  const chartData = forecast
    ? forecast.days.map((day, idx) => ({
        day,
        Base: Math.round(forecast.base_case[idx]),
        Worst: Math.round(forecast.worst_case[idx]),
        Best: Math.round(forecast.best_case[idx]),
      }))
    : [];

  const daysRemainingWorst = forecast
    ? forecast.days.find((_, idx) => forecast.worst_case[idx] < reserveFloor) ?? 90
    : 90;

  const currentRunwayBase = forecast
    ? forecast.days.find((_, idx) => forecast.base_case[idx] < reserveFloor) ?? 90
    : 90;

  return (
    <div className="space-y-6" data-theme={theme} data-font={font}>
      {/* Top Header */}
      <section className="rounded-2xl border border-[var(--border-secondary)] bg-[var(--bg-overlay)] p-6">
        <div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between">
          <div className="flex gap-4">
            <div className="grid h-12 w-12 place-items-center rounded-xl bg-credit-line-500/10 text-credit-line-500">
              <Cpu size={24} />
            </div>
            <div>
              <p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-[var(--text-tertiary)]">Executive Strategy Room</p>
              <h2 className="mt-2 text-2xl font-bold font-display text-[var(--text-primary)]">Autonomous CFO Cockpit</h2>
              <p className="mt-2 max-w-2xl text-xs text-[var(--text-secondary)] leading-relaxed">
                90-day predictive time-series liquidity forecasting, document RAG compliance checking, and autonomous negotiation agent swarm tracking.
              </p>
            </div>
          </div>
          <div className="flex gap-2">
            <button
              onClick={() => setActiveTab('forecasting')}
              className={cn("btn-secondary text-xs px-4 py-2 flex items-center gap-1.5", activeTab === 'forecasting' && "bg-[var(--text-primary)] text-[var(--text-inverse)] hover:bg-[var(--text-secondary)]")}
            >
              <BarChart3 size={13} /> Forecast & Sliders
            </button>
            <button
              onClick={() => setActiveTab('inbox')}
              className={cn("btn-secondary text-xs px-4 py-2 flex items-center gap-1.5 relative", activeTab === 'inbox' && "bg-[var(--text-primary)] text-[var(--text-inverse)] hover:bg-[var(--text-secondary)]")}
            >
              <Inbox size={13} /> Strategy Inbox
              {inbox.filter(i => i.status === 'PENDING').length > 0 && (
                <span className="absolute -top-1 -right-1 flex h-4 w-4 items-center justify-center rounded-full bg-risk-high text-[8px] font-bold text-white leading-none">
                  {inbox.filter(i => i.status === 'PENDING').length}
                </span>
              )}
            </button>
            <button
              onClick={() => setActiveTab('rag')}
              className={cn("btn-secondary text-xs px-4 py-2 flex items-center gap-1.5", activeTab === 'rag' && "bg-[var(--text-primary)] text-[var(--text-inverse)] hover:bg-[var(--text-secondary)]")}
            >
              <Layers size={13} /> RAG Contract Audit
            </button>
          </div>
        </div>
      </section>

      {/* CFO Key Metrics Row */}
      <section className="grid gap-4 md:grid-cols-4">
        <div className="rounded-2xl border border-[var(--border-secondary)] bg-[var(--bg-card)] p-5 space-y-1.5 shadow-sm">
          <span className="text-[10px] font-bold uppercase tracking-wider text-[var(--text-tertiary)]">liquidity runway (worst)</span>
          <p className="text-3xl font-black font-mono text-[var(--text-primary)] flex items-baseline gap-1">
            {daysRemainingWorst >= 90 ? '90+' : daysRemainingWorst}
            <span className="text-xs font-semibold text-[var(--text-tertiary)] font-sans">days</span>
          </p>
          <span className="block text-[10px] text-risk-medium flex items-center gap-1">
            <AlertTriangle size={10} /> Projected threshold breach on Day {daysRemainingWorst}
          </span>
        </div>

        <div className="rounded-2xl border border-[var(--border-secondary)] bg-[var(--bg-card)] p-5 space-y-1.5 shadow-sm">
          <span className="text-[10px] font-bold uppercase tracking-wider text-[var(--text-tertiary)]">projected reserve deficit</span>
          <p className="text-3xl font-black font-mono text-risk-medium">
            {forecast && forecast.worst_case[89] < reserveFloor
              ? `₹${Math.round((reserveFloor - forecast.worst_case[89]) / 1000)}K`
              : '₹0.00'}
          </p>
          <span className="block text-[10px] text-[var(--text-tertiary)]">At 90-day worst-case boundary</span>
        </div>

        <div className="rounded-2xl border border-[var(--border-secondary)] bg-[var(--bg-card)] p-5 space-y-1.5 shadow-sm">
          <span className="text-[10px] font-bold uppercase tracking-wider text-[var(--text-tertiary)]">active contracts in RAG</span>
          <p className="text-3xl font-black font-mono text-[var(--text-primary)]">2</p>
          <span className="block text-[10px] text-emerald-500 flex items-center gap-1">
            <ShieldCheck size={10} /> Local vector embeddings synced
          </span>
        </div>

        <div className="rounded-2xl border border-[var(--border-secondary)] bg-[var(--bg-card)] p-5 space-y-1.5 shadow-sm">
          <span className="text-[10px] font-bold uppercase tracking-wider text-[var(--text-tertiary)]">negotiations pending</span>
          <p className="text-3xl font-black font-mono text-credit-line-500">
            {inbox.filter(i => i.status === 'PENDING').length}
          </p>
          <span className="block text-[10px] text-[var(--text-tertiary)]">Queued for 1-click CFO approval</span>
        </div>
      </section>

      {/* Main стратегические панели */}
      {activeTab === 'forecasting' && (
        <div className="grid grid-cols-12 gap-6">
          {/* Sliders Panel */}
          <div className="col-span-12 lg:col-span-4 rounded-2xl border border-[var(--border-secondary)] bg-[var(--bg-card)] p-6 space-y-6">
            <h3 className="text-sm font-bold uppercase tracking-wider text-[var(--text-primary)] flex items-center gap-1.5 border-b border-[var(--border-secondary)] pb-3">
              <Sliders size={15} /> Stress-Test Parameters
            </h3>

            {/* Growth Slider */}
            <div className="space-y-2">
              <div className="flex justify-between text-xs font-semibold">
                <span className="text-[var(--text-secondary)]">Revenue Growth Shift</span>
                <span className={salesGrowth >= 0 ? "text-emerald-500" : "text-risk-high"}>
                  {salesGrowth >= 0 ? '+' : ''}{(salesGrowth * 100).toFixed(0)}%
                </span>
              </div>
              <input
                type="range"
                min="-0.2"
                max="0.5"
                step="0.05"
                value={salesGrowth}
                onChange={(e) => setSalesGrowth(parseFloat(e.target.value))}
                className="w-full h-1 bg-[var(--border-secondary)] rounded-lg appearance-none cursor-pointer accent-credit-line-500"
              />
              <span className="block text-[9px] text-[var(--text-tertiary)]">Simulates monthly customer sign-up swings.</span>
            </div>

            {/* Churn Slider */}
            <div className="space-y-2">
              <div className="flex justify-between text-xs font-semibold">
                <span className="text-[var(--text-secondary)]">Customer Churn Drag</span>
                <span className={churnRate > 0 ? "text-risk-medium" : "text-emerald-500"}>
                  {(churnRate * 100).toFixed(0)}%
                </span>
              </div>
              <input
                type="range"
                min="0.0"
                max="0.4"
                step="0.02"
                value={churnRate}
                onChange={(e) => setChurnRate(parseFloat(e.target.value))}
                className="w-full h-1 bg-[var(--border-secondary)] rounded-lg appearance-none cursor-pointer accent-credit-line-500"
              />
              <span className="block text-[9px] text-[var(--text-tertiary)]">Simulates base portfolio contraction rate.</span>
            </div>

            {/* Macro Rate Shock */}
            <div className="space-y-2">
              <div className="flex justify-between text-xs font-semibold">
                <span className="text-[var(--text-secondary)]">Macro Interest Rate Shift (SOFR)</span>
                <span className="text-accent-purple">
                  {interestShock >= 0 ? '+' : ''}{interestShock} bps
                </span>
              </div>
              <input
                type="range"
                min="-200"
                max="200"
                step="25"
                value={interestShock}
                onChange={(e) => setInterestShock(parseInt(e.target.value))}
                className="w-full h-1 bg-[var(--border-secondary)] rounded-lg appearance-none cursor-pointer accent-credit-line-500"
              />
              <span className="block text-[9px] text-[var(--text-tertiary)]">Federal Reserve baseline interest rate shocks.</span>
            </div>

            {/* Reserve Floor Slider */}
            <div className="space-y-2">
              <div className="flex justify-between text-xs font-semibold">
                <span className="text-[var(--text-secondary)]">Required Cash Reserves Floor</span>
                <span className="font-mono text-[var(--text-primary)]">
                  ₹{(reserveFloor / 100000).toFixed(1)}L
                </span>
              </div>
              <input
                type="range"
                min="500000"
                max="2500000"
                step="100000"
                value={reserveFloor}
                onChange={(e) => setReserveFloor(parseInt(e.target.value))}
                className="w-full h-1 bg-[var(--border-secondary)] rounded-lg appearance-none cursor-pointer accent-credit-line-500"
              />
              <span className="block text-[9px] text-[var(--text-tertiary)]">Target floor triggers automated negotiator emails.</span>
            </div>

            <button
              onClick={() => runForecast()}
              disabled={loadingForecast}
              className="w-full text-xs font-bold py-3 rounded-2xl bg-[var(--text-primary)] text-[var(--text-inverse)] hover:bg-[var(--text-secondary)] flex items-center justify-center gap-2 transition-all mt-4 disabled:opacity-50"
            >
              {loadingForecast ? <RefreshCw size={13} className="animate-spin" /> : <RefreshCw size={13} />}
              Compute Liquidity Forecast
            </button>
          </div>

          {/* Forecasting Graph Chart */}
          <div className="col-span-12 lg:col-span-8 rounded-2xl border border-[var(--border-secondary)] bg-[var(--bg-card)] p-6 space-y-4">
            <div className="flex items-center justify-between">
              <div>
                <h3 className="text-sm font-bold uppercase tracking-wider text-[var(--text-primary)]">90-Day Predictive Cash Flow Runway</h3>
                <span className="text-[10px] text-[var(--text-tertiary)]">Multivariate temporal neural network LSTM predictions</span>
              </div>
              {forecast && forecast.trigger_report.triggered && (
                <span className="badge text-[10px] text-risk-high bg-risk-high/10 border border-risk-high/20 px-2 py-0.5 animate-pulse flex items-center gap-1">
                  <ShieldAlert size={11} /> Deficit Warning Active
                </span>
              )}
            </div>

            {/* Recharts Forecast Graph */}
            <div className="h-72 w-full pt-4 font-mono text-[10px]">
              <ResponsiveContainer width="100%" height="100%">
                <AreaChart data={chartData} margin={{ top: 10, right: 10, left: 10, bottom: 0 }}>
                  <defs>
                    <linearGradient id="colorBest" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#4eba7a" stopOpacity={0.15}/>
                      <stop offset="95%" stopColor="#4eba7a" stopOpacity={0.0}/>
                    </linearGradient>
                    <linearGradient id="colorWorst" x1="0" y1="0" x2="0" y2="1">
                      <stop offset="5%" stopColor="#df7c3c" stopOpacity={0.15}/>
                      <stop offset="95%" stopColor="#df7c3c" stopOpacity={0.0}/>
                    </linearGradient>
                  </defs>
                  <CartesianGrid strokeDasharray="3 3" stroke="var(--border-secondary)" opacity={0.3} />
                  <XAxis dataKey="day" stroke="var(--text-tertiary)" tickLine={false} label={{ value: 'Forecast horizon (days)', position: 'insideBottom', offset: -5, fill: 'var(--text-tertiary)' }} />
                  <YAxis
                    stroke="var(--text-tertiary)"
                    tickLine={false}
                    tickFormatter={(val) => `₹${(val / 100000).toFixed(1)}L`}
                  />
                  <Tooltip
                    contentStyle={{
                      backgroundColor: 'var(--bg-overlay)',
                      borderColor: 'var(--border-secondary)',
                      color: 'var(--text-primary)',
                      borderRadius: '12px'
                    }}
                    formatter={(value) => [`₹${Number(value).toLocaleString('en-IN')}`, '']}
                  />
                  <ReferenceLine y={reserveFloor} stroke="red" strokeDasharray="3 3" label={{ value: 'Reserve Floor', fill: 'red', position: 'top', fontSize: 10 }} />
                  
                  {/* Probability Envelopes */}
                  <Area type="monotone" dataKey="Best" stroke="#4eba7a" strokeWidth={1.5} fillOpacity={1} fill="url(#colorBest)" name="Best Case (90th %)" />
                  <Area type="monotone" dataKey="Base" stroke="var(--text-primary)" strokeWidth={2} fill="none" name="Base Case (Forecast)" />
                  <Area type="monotone" dataKey="Worst" stroke="#df7c3c" strokeWidth={1.5} fillOpacity={1} fill="url(#colorWorst)" name="Worst Case (10th %)" />
                </AreaChart>
              </ResponsiveContainer>
            </div>

            <div className="border-t border-[var(--border-secondary)] pt-4 flex flex-wrap gap-4 text-[10px] font-medium text-[var(--text-secondary)] justify-between">
              <div className="flex items-center gap-2">
                <span className="w-3 h-3 rounded bg-white border border-gray-400 inline-block" />
                <span>Base Forecast: runway {currentRunwayBase} days</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="w-3 h-3 rounded bg-[#4eba7a] inline-block" />
                <span>Best Case scenario</span>
              </div>
              <div className="flex items-center gap-2">
                <span className="w-3 h-3 rounded bg-[#df7c3c] inline-block" />
                <span>Worst Case scenario: runway {daysRemainingWorst} days</span>
              </div>
              <div className="text-[var(--text-tertiary)] max-w-xs text-right leading-relaxed">
                * Predictions updated using historical moving average covariance indexes.
              </div>
            </div>
          </div>
        </div>
      )}

      {activeTab === 'inbox' && (
        <div className="grid grid-cols-12 gap-6">
          {/* Inbox List (Left 4 cols) */}
          <div className="col-span-12 lg:col-span-4 rounded-2xl border border-[var(--border-secondary)] bg-[var(--bg-card)] p-4 space-y-3 max-h-[580px] overflow-y-auto">
            <h3 className="text-xs font-bold uppercase tracking-wider text-[var(--text-primary)] flex items-center gap-1.5 border-b border-[var(--border-secondary)] pb-3 px-1">
              <Inbox size={15} /> Strategic Tasks Inbox
            </h3>

            {inbox.length === 0 ? (
              <div className="text-center py-10">
                <Inbox size={24} className="mx-auto text-[var(--text-tertiary)] opacity-35" />
                <p className="text-xs text-[var(--text-secondary)] mt-2">Inbox is clear</p>
                <p className="text-[9px] text-[var(--text-tertiary)] mt-1">Run scenario simulation to trigger checks.</p>
              </div>
            ) : (
              inbox.map((item) => (
                <button
                  key={item.id}
                  onClick={() => setSelectedInboxItem(item)}
                  className={cn(
                    "w-full text-left p-3.5 rounded-xl border transition-all flex flex-col space-y-1.5",
                    selectedInboxItem?.id === item.id
                      ? "border-credit-line-500 bg-credit-line-500/5 shadow-sm"
                      : "border-[var(--border-secondary)] hover:bg-[var(--bg-secondary)]/50 bg-[var(--bg-secondary)]/25",
                    item.status === 'APPROVED' && "border-emerald-500/20 bg-emerald-500/5 opacity-80"
                  )}
                >
                  <div className="flex justify-between items-center">
                    <span className="text-[9px] font-mono font-bold text-[var(--text-tertiary)]">{item.id}</span>
                    <span className={cn(
                      "text-[8px] font-extrabold uppercase px-2 py-0.5 rounded-full border",
                      item.status === 'PENDING' && "bg-risk-medium/15 text-risk-medium border-risk-medium/20",
                      item.status === 'APPROVED' && "bg-emerald-500/15 text-emerald-500 border-emerald-500/25",
                      item.status === 'REJECTED' && "bg-risk-high/15 text-risk-high border-risk-high/25"
                    )}>
                      {item.status}
                    </span>
                  </div>
                  <h4 className="text-xs font-bold text-[var(--text-primary)] truncate">{item.title}</h4>
                  <div className="flex justify-between text-[9px] text-[var(--text-secondary)]">
                    <span>{item.type === 'term_negotiation' ? 'Term Outreach' : 'Asset Cuts'}</span>
                    <span>{new Date(item.created_at).toLocaleDateString()}</span>
                  </div>
                </button>
              ))
            )}
          </div>

          {/* Action Viewer Detail (Right 8 cols) */}
          <div className="col-span-12 lg:col-span-8 rounded-2xl border border-[var(--border-secondary)] bg-[var(--bg-card)] p-6 space-y-6 min-h-[480px]">
            {selectedInboxItem ? (
              <div className="space-y-6 h-full flex flex-col justify-between">
                <div>
                  <div className="flex justify-between items-start border-b border-[var(--border-secondary)] pb-4">
                    <div>
                      <span className="text-[10px] font-mono text-credit-line-500 uppercase tracking-widest">{selectedInboxItem.type.replace('_', ' ')}</span>
                      <h3 className="text-base font-bold text-[var(--text-primary)] mt-1">{selectedInboxItem.title}</h3>
                    </div>
                    <span className="text-xs text-[var(--text-tertiary)]">
                      Logged {new Date(selectedInboxItem.created_at).toLocaleTimeString()}
                    </span>
                  </div>

                  {selectedInboxItem.type === 'term_negotiation' ? (
                    /* Vendor email negotiations */
                    <div className="space-y-4 pt-4">
                      <div className="grid grid-cols-2 gap-4">
                        <div className="rounded-xl border border-[var(--border-secondary)] bg-[var(--bg-secondary)] p-3 space-y-1">
                          <span className="text-[9px] font-bold uppercase tracking-wider text-[var(--text-tertiary)]">supplier vendor</span>
                          <p className="text-xs font-bold text-[var(--text-primary)]">{selectedInboxItem.vendor}</p>
                        </div>
                        <div className="rounded-xl border border-[var(--border-secondary)] bg-[var(--bg-secondary)] p-3 space-y-1">
                          <span className="text-[9px] font-bold uppercase tracking-wider text-[var(--text-tertiary)]">proposed terms</span>
                          <p className="text-xs font-bold text-emerald-500">
                            {selectedInboxItem.current_terms} → {selectedInboxItem.proposed_terms}
                          </p>
                        </div>
                      </div>

                      <div className="space-y-2">
                        <span className="text-xs font-bold text-[var(--text-primary)]">Email Subject:</span>
                        <div className="rounded-xl border border-[var(--border-secondary)] bg-[var(--bg-secondary)] p-3 text-xs font-mono text-[var(--text-secondary)]">
                          {selectedInboxItem.email_subject}
                        </div>
                      </div>

                      <div className="space-y-2">
                        <div className="flex justify-between items-center">
                          <span className="text-xs font-bold text-[var(--text-primary)]">Outreach Message Body (Editable):</span>
                          {selectedInboxItem.status === 'APPROVED' && (
                            <span className="text-[9px] text-emerald-500 flex items-center gap-1">
                              <CheckCircle2 size={11} /> Sent via Auto-SMTP Server
                            </span>
                          )}
                        </div>
                        <textarea
                          disabled={selectedInboxItem.status !== 'PENDING'}
                          value={editedEmailBody}
                          onChange={(e) => setEditedEmailBody(e.target.value)}
                          className="w-full h-48 rounded-xl border border-[var(--border-secondary)] bg-[var(--bg-secondary)] p-4 text-xs font-mono text-[var(--text-secondary)] focus:outline-none focus:border-credit-line-500 leading-relaxed"
                        />
                      </div>
                    </div>
                  ) : (
                    /* Budget cut recommendation cuts */
                    <div className="space-y-4 pt-4">
                      <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
                        {selectedInboxItem.description}
                      </p>

                      <div className="border border-[var(--border-primary)] rounded-xl overflow-hidden divide-y divide-[var(--border-secondary)]">
                        <div className="grid grid-cols-12 gap-2 bg-[var(--bg-secondary)] p-3 text-[10px] uppercase font-bold tracking-wider text-[var(--text-tertiary)]">
                          <div className="col-span-4">Department</div>
                          <div className="col-span-3 text-right">Original</div>
                          <div className="col-span-3 text-right">Proposed</div>
                          <div className="col-span-2 text-right">Cut %</div>
                        </div>

                        {selectedInboxItem.cuts?.map((cut) => (
                          <div key={cut.department} className="grid grid-cols-12 gap-2 p-3 text-xs items-center hover:bg-[var(--bg-secondary)]/20 transition-colors">
                            <div className="col-span-4 space-y-0.5">
                              <strong className="block text-[var(--text-primary)]">{cut.department}</strong>
                              <span className="block text-[9px] text-[var(--text-tertiary)] font-mono">{cut.action}</span>
                            </div>
                            <div className="col-span-3 text-right font-mono text-[var(--text-secondary)]">₹{(cut.original / 100000).toFixed(1)}L</div>
                            <div className="col-span-3 text-right font-mono text-emerald-500 font-bold">₹{(cut.proposed / 100000).toFixed(1)}L</div>
                            <div className="col-span-2 text-right text-risk-medium font-bold">-{cut.reduction_pct}%</div>
                          </div>
                        ))}
                      </div>

                      <div className="rounded-xl bg-credit-line-500/5 border border-credit-line-500/10 p-4 flex justify-between items-center text-xs">
                        <span className="font-semibold text-[var(--text-secondary)]">Total Projected Reserves Savings:</span>
                        <strong className="font-mono text-base text-credit-line-500">
                          ₹{selectedInboxItem.total_savings ? (selectedInboxItem.total_savings / 100000).toFixed(2) : 0}L
                        </strong>
                      </div>
                    </div>
                  )}

                  {/* Actions buttons */}
                  {selectedInboxItem.status === 'PENDING' ? (
                    <div className="flex gap-2 justify-end pt-4 border-t border-[var(--border-secondary)] mt-6">
                      <button
                        onClick={() => handleAction(selectedInboxItem.id, 'REJECT')}
                        className="btn-secondary text-xs px-4 py-2 text-risk-high flex items-center gap-1"
                      >
                        <X size={13} /> Archive Recommendation
                      </button>
                      <button
                        onClick={() => handleAction(selectedInboxItem.id, 'APPROVE')}
                        className="btn-dark text-xs px-5 py-2 flex items-center gap-1"
                      >
                        <Send size={13} /> {selectedInboxItem.type === 'term_negotiation' ? 'Approve & Send Email' : 'Execute Budget Rebalancing'}
                      </button>
                    </div>
                  ) : (
                    <div className="p-3 text-center border-t border-[var(--border-secondary)] mt-6 bg-[var(--bg-secondary)]/35 text-[10px] font-semibold text-[var(--text-tertiary)] rounded-xl uppercase tracking-wider">
                      Decision locked as {selectedInboxItem.status} at {selectedInboxItem.processed_at ? new Date(selectedInboxItem.processed_at).toLocaleTimeString() : 'N/A'}
                    </div>
                  )}
                </div>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-20 text-center text-[var(--text-tertiary)]">
                <Inbox size={32} className="opacity-25" />
                <p className="text-xs font-bold mt-2">Select a Strategy Action Item</p>
                <p className="text-[9px] mt-1">Review queued vendor outreach drafts or budget cuts.</p>
              </div>
            )}
          </div>
        </div>
      )}

      {activeTab === 'rag' && (
        <div className="grid grid-cols-12 gap-6 animate-fade-in">
          {/* Left Contract Input Column */}
          <div className="col-span-12 lg:col-span-5 rounded-2xl border border-[var(--border-secondary)] bg-[var(--bg-card)] p-6 space-y-4 flex flex-col justify-between">
            <div className="space-y-2">
              <h3 className="text-sm font-bold uppercase tracking-wider text-[var(--text-primary)] flex items-center gap-1.5">
                <UploadCloud size={15} className="text-credit-line-500" /> Contract RAG Ingestion Portal
              </h3>
              <p className="text-xs text-[var(--text-secondary)] leading-relaxed">
                Paste supplier Master Service Agreements (MSAs) or lease agreements. The TF-IDF vector index will segment contract conditions to audit ledger timeline deviations.
              </p>
            </div>

            <div className="space-y-1.5 flex-1 mt-2">
              <label className="text-[10px] font-bold text-[var(--text-tertiary)] uppercase tracking-wider">contract reference filename:</label>
              <input
                type="text"
                value={contractFile}
                onChange={(e) => setContractFile(e.target.value)}
                placeholder="vnd_consult_agreement_2026.txt"
                className="w-full rounded-lg border border-[var(--border-secondary)] bg-[var(--bg-secondary)] px-3 py-2 text-xs font-mono mb-2"
              />
              <textarea
                value={contractText}
                onChange={(e) => setContractText(e.target.value)}
                placeholder="Paste contract contents..."
                className="w-full h-80 rounded-xl border border-[var(--border-secondary)] bg-[var(--bg-secondary)] p-3 text-xs font-mono leading-relaxed"
              />
            </div>

            <button
              onClick={runContractAudit}
              disabled={loadingAudit || !contractText.trim()}
              className="w-full text-xs font-bold py-3 rounded-2xl bg-credit-line-500 text-white hover:bg-credit-line-600 flex items-center justify-center gap-2 transition-all mt-4 disabled:opacity-50"
            >
              {loadingAudit ? <RefreshCw size={13} className="animate-spin" /> : <ShieldCheck size={13} />}
              Ingest & Audit Contract Ledger
            </button>
          </div>

          {/* Right Audit Results */}
          <div className="col-span-12 lg:col-span-7 rounded-2xl border border-[var(--border-secondary)] bg-[var(--bg-card)] p-6 space-y-6">
            <div>
              <h3 className="text-sm font-bold uppercase tracking-wider text-[var(--text-primary)]">RAG Audit Compliance Ledger</h3>
              <span className="text-[10px] text-[var(--text-tertiary)]">Ledger cross-referenced with vector-extracted contract parameters</span>
            </div>

            {auditResult ? (
              <div className="space-y-5 animate-fade-in">
                {/* RAG summary card */}
                <div className="grid grid-cols-3 gap-3">
                  <div className="rounded-xl border border-[var(--border-secondary)] bg-[var(--bg-secondary)]/50 p-3 space-y-1">
                    <span className="text-[9px] font-bold uppercase text-[var(--text-tertiary)]">detected payment terms</span>
                    <strong className="block text-xs text-credit-line-500 font-mono">{auditResult.detected_terms}</strong>
                  </div>
                  <div className="rounded-xl border border-[var(--border-secondary)] bg-[var(--bg-secondary)]/50 p-3 space-y-1">
                    <span className="text-[9px] font-bold uppercase text-[var(--text-tertiary)]">extract target days</span>
                    <strong className="block text-xs text-[var(--text-primary)] font-mono">{auditResult.extracted_days} days</strong>
                  </div>
                  <div className="rounded-xl border border-[var(--border-secondary)] bg-[var(--bg-secondary)]/50 p-3 space-y-1">
                    <span className="text-[9px] font-bold uppercase text-[var(--text-tertiary)]">semantic match metric</span>
                    <strong className="block text-xs text-emerald-500 font-mono">{(auditResult.match_confidence * 100).toFixed(0)}%</strong>
                  </div>
                </div>

                <div className="rounded-xl border border-[var(--border-secondary)] bg-[var(--bg-secondary)]/35 p-3 space-y-1.5">
                  <div className="flex gap-1.5 items-center text-[10px] font-bold text-credit-line-500 uppercase tracking-widest">
                    <Info size={11} /> matched clause text:
                  </div>
                  <blockquote className="text-xs text-[var(--text-secondary)] italic leading-relaxed pl-2 border-l border-credit-line-500/30">
                    "...{auditResult.clause}..."
                  </blockquote>
                </div>

                {/* Ledger Audit Table */}
                <div className="space-y-3">
                  <div className="flex justify-between items-center">
                    <h4 className="text-xs font-bold text-[var(--text-primary)]">Discrepancies & Violations Identified</h4>
                    <span className={cn(
                      "badge text-[9px] font-bold",
                      auditResult.violations_count > 0 ? "bg-risk-high/15 text-risk-high" : "bg-emerald-500/15 text-emerald-500"
                    )}>
                      {auditResult.violations_count} deviations flagged
                    </span>
                  </div>

                  {auditResult.violations.length === 0 ? (
                    <div className="p-10 border border-dashed border-[var(--border-secondary)] rounded-xl text-center text-xs text-[var(--text-secondary)]">
                      ✓ Zero late-payment SLA violations detected. Ledger matches contract payment cycles perfectly.
                    </div>
                  ) : (
                    <div className="space-y-2 max-h-[220px] overflow-y-auto pr-1">
                      {auditResult.violations.map((v, idx) => (
                        <div key={idx} className="p-3 border border-risk-high/10 bg-risk-high/5 rounded-xl text-xs space-y-1">
                          <div className="flex justify-between">
                            <strong className="text-[var(--text-primary)]">Invoice {v.invoice_ref} (₹28.4L)</strong>
                            <span className="text-[9px] font-bold text-risk-high border border-risk-high/20 px-2 py-0.5 rounded-full uppercase">
                              {v.status.replace(/_/g, ' ')}
                            </span>
                          </div>
                          <div className="flex justify-between text-[10px] text-[var(--text-secondary)] font-mono">
                            <span>Billed: {v.invoice_date}</span>
                            <span>Paid: {v.payment_date}</span>
                            <span className="text-risk-high font-bold">{v.days_to_pay} days taken ({v.excess_days} days late!)</span>
                          </div>
                          <div className="text-[9px] text-[var(--text-tertiary)] italic">
                            * Contract strictly demands settlement within {v.allowed_days} days of the billing timestamp.
                          </div>
                        </div>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            ) : (
              <div className="flex flex-col items-center justify-center py-24 border border-dashed border-[var(--border-secondary)] rounded-2xl text-center text-[var(--text-tertiary)]">
                <FileText size={40} className="opacity-20 animate-pulse" />
                <p className="text-xs font-bold mt-3">RAG Audit Results Pending</p>
                <p className="text-[9px] mt-1">Provide supplier agreement text on the left and trigger audit analysis.</p>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Float Toasts System */}
      <div className="fixed bottom-6 right-6 z-50 space-y-2 w-96 font-sans">
        {toasts.map((t) => (
          <div
            key={t.id}
            className={cn(
              "p-4 rounded-xl border shadow-2xl flex items-start gap-3 backdrop-blur-xl animate-slide-in text-xs font-semibold leading-relaxed",
              t.type === 'success' && "bg-emerald-500/10 border-emerald-500/30 text-emerald-600 dark:text-emerald-400",
              t.type === 'error' && "bg-risk-high/10 border-risk-high/30 text-risk-high",
              t.type === 'info' && "bg-credit-line-500/10 border-credit-line-500/30 text-credit-line-500"
            )}
          >
            <div className="shrink-0 mt-0.5">
              {t.type === 'success' && <CheckCircle2 size={15} />}
              {t.type === 'error' && <AlertTriangle size={15} />}
              {t.type === 'info' && <Info size={15} />}
            </div>
            <p className="flex-1">{t.message}</p>
          </div>
        ))}
      </div>
    </div>
  );
}
